### ISSUE TITLE
Queries with Subqueries Fail When Using Bindings

### ISSUE THREAD

**Issue by tjcelaya** [pixelfederation/vitess-php-pdo#8]
Prepared statements including subqueries fail with the error: "unsupported: subquery and parent route to different shards"

For example, the following query runs just fine if 100 is hardcoded or the query is run through adminer (our sharding key is account_id):

```
SELECT count(*) as AGGREGATE
FROM `orders`
WHERE `orders`.`account_id` = 100
AND 1 < (
  SELECT count(*)
  FROM `invoices`
  WHERE `invoices`.`account_id` = 100
    AND `invoices`.`order_id` = `orders`.`id`)
```

But the moment it is used as a prepared statement, either by replacing both instances of 100 with bindings or a single instance, we receive the above error. Any help would be greatly appreciated!

**Comment by enisoc** [comment]
When you try it as a prepared statement, do you use positional parameters (`?`), or named parameters (`:account_id`)? I think it should work if you use named parameters, and refer to the same named parameter in both places in the query.

This type of query can't work for positional parameters because then there's no guarantee that you'll provide the same value for both. Vitess routing plans for queries with bind variables have to be valid no matter what values are passed for those bind variables. That's because the plan is cached so that it doesn't have to be re-computed when you send the same query with different values for the bind variables.

**Comment by tjcelaya** [comment]
@enisoc Thanks for the insight! We're now investigating changing our query builder to use named parameters.
